<?php
/**
 * Created by PhpStorm.
 * User: Nidhal
 * Date: 19/03/2018
 * Time: 23:03
 */

namespace App\PIBundle\Repository;

/**
 * SujetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HoraireRepository extends \Doctrine\ORM\EntityRepository
{
    public function findHoraire($p)
    {

        $query=$this->getEntityManager()->createQuery(
            "select h from AppPIBundle:Horaire h WHERE h.idProp=:nbp 
             "
        )->setParameter('nbp',$p);
        return $query->getResult();

    }
}
