main_homepage:
    path:     /x
    defaults: { _controller: MainBundle:Default:index }

home:
    path:     /
    defaults: { _controller: MainBundle:Main:index }

detail:
    path:     /detail/{idProduct}
    defaults: { _controller: MainBundle:Main:detail }

panier:
    path:     /panier
    defaults: { _controller: MainBundle:Main:panier }

rech:
    path:     /recherche
    defaults: { _controller: MainBundle:Main:rech }

